# Generated by Django 2.2 on 2021-03-01 06:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='assignments',
            new_name='Assignment',
        ),
        migrations.RenameModel(
            old_name='messages',
            new_name='Message',
        ),
        migrations.RenameModel(
            old_name='students',
            new_name='Student',
        ),
        migrations.RenameModel(
            old_name='subjects',
            new_name='Subject',
        ),
        migrations.RenameModel(
            old_name='Users',
            new_name='User',
        ),
    ]
