# Generated by Django 3.1.5 on 2021-02-28 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='messages',
            new_name='inbox_messages',
        ),
    ]
